export const REQUEST_SEARCH_MOVIE = 'search/ REQUEST SEARCH MOVIE';
export const SEARCH_MOVIE_START = 'search/ SEARCH MOVIE START';
export const SEARCH_MOVIE_SUCCESS = 'search/ SEARCH MOVIE SUCCESS';
export const SEARCH_MOVIE_FAIL = 'search/ SEARCH MOVIE FAIL';
export const SEARCH_QUERY_INPUT = 'search/ SEARCH QUERY INPUT';
