export const REQUEST_FETCH_TRENDING_MOVIES = 'movies/ REQUEST FETCH TRENDING MOVIES';
export const FETCH_TRENDING_MOVIES_SUCCESS = 'movies/ FETCH TRENDING MOVIES SUCCESS';
export const FETCH_TRENDING_MOVIES_FAIL = 'movies/ FETCH TRENDING MOVIES FAIL';

export const REQUEST_FETCH_MOVIE_DETAILS = 'movies/ REQUEST FETCH MOVIE DETAILS';
export const FETCH_MOVIE_DETAILS_SUCCESS = 'movies/ FETCH MOVIE DETAILS SUCCESS';
export const FETCH_MOVIE_DETAILS_FAIL = 'movies/ FETCH MOVIE DETAILS FAIL';
