export const REQUEST_FETCH_TRENDING_MOVIES = 'movies/ REQUEST FETCH TRENDING MOVIES';
export const FETCH_TRENDING_MOVIES_SUCCESS = 'movies/ FETCH TRENDING MOVIES SUCCESS';
export const FETCH_TRENDING_MOVIES_FAIL = 'movies/ FETCH TRENDING MOVIES FAIL';

export const REQUEST_FETCH_MOVIE_DETAILS = 'movies/ REQUEST FETCH MOVIE DETAILS';
export const FETCH_MOVIE_DETAILS_SUCCESS = 'movies/ FETCH MOVIE DETAILS SUCCESS';
export const FETCH_MOVIE_DETAILS_FAIL = 'movies/ FETCH MOVIE DETAILS FAIL';

export const REQUEST_FETCH_MOVIE_CAST = 'movies/ REQUEST FETCH MOVIE CAST';
export const FETCH_MOVIE_CAST_SUCCESS = 'movies/ FETCH MOVIE CAST SUCCESS';
export const FETCH_MOVIE_CAST_FAIL = 'movies/ FETCH MOVIE CAST FAIL';
export const SHOW_FULL_CAST = 'movies/ SHOW FULL CAST';
export const CLEAR_MOVIE_CAST = 'movies/ CLEAR MOVIE CAST';

export const REQUEST_FETCH_TOP_MOVIES = 'movies/ REQUEST FETCH TOP MOVIES';
export const FETCH_TOP_MOVIES_SUCCESS = 'movies/ FETCH TOP MOVIES SUCCESS';
export const FETCH_TOP_MOVIES_FAIL = 'movies/ FETCH TOP MOVIES FAIL';

export const REQUEST_FETCH_PLAYING_MOVIES = 'movies/ REQUEST FETCH PLAYING MOVIES';
export const FETCH_PLAYING_MOVIES_SUCCESS = 'movies/ FETCH PLAYING MOVIES SUCCESS';
export const FETCH_PLAYING_MOVIES_FAIL = 'movies/ FETCH PLAYING MOVIES FAIL';

export const SELECT_TAB = 'movies/ SELECT TAB';
