export const REQUEST_FETCH_TRENDING_TV = 'tv/ REQUEST FETCH TRENDING TV';
export const FETCH_TRENDING_TV_SUCCESS = 'tv/ FETCH TRENDING TV SUCCESS';
export const FETCH_TRENDING_TV_FAIL = 'tv/ FETCH TRENDING TV FAIL';

export const REQUEST_FETCH_TOP_TV = 'tv/ REQUEST FETCH TOP TV';
export const FETCH_TOP_TV_SUCCESS = 'tv/ FETCH TOP TV SUCCESS';
export const FETCH_TOP_TV_FAIL = 'tv/ FETCH TOP TV FAIL';
