export const REQUEST_FETCH_TRENDING_TV = 'tv/ REQUEST FETCH TRENDING TV';
export const FETCH_TRENDING_TV_SUCCESS = 'tv/ FETCH TRENDING TV SUCCESS';
export const FETCH_TRENDING_TV_FAIL = 'tv/ FETCH TRENDING TV FAIL';

export const REQUEST_FETCH_TOP_TV = 'tv/ REQUEST FETCH TOP TV';
export const FETCH_TOP_TV_SUCCESS = 'tv/ FETCH TOP TV SUCCESS';
export const FETCH_TOP_TV_FAIL = 'tv/ FETCH TOP TV FAIL';

export const REQUEST_FETCH_TV_DETAILS = 'tv/ REQUEST FETCH TV DETAILS';
export const FETCH_TV_DETAILS_SUCCESS = 'tv/ FETCH TV DETAILS_SUCCESS';
export const FETCH_TV_DETAILS_FAIL = 'tv/ FETCH TV DETAILS_FAIL';
