export const REQUEST_FETCH_POPULAR_PEOPLE =
  "people/ REQUEST FETCH POPULAR PEOPLE";
export const FETCH_POPULAR_PEOPLE_SUCCESS =
  "people/ FETCH POPULAR PEOPLE SUCCESS";
export const FETCH_POPULAR_PEOPLE_FAIL = "people/ FETCH POPULAR PEOPLE FAIL";

export const REQUEST_FETCH_PEOPLE_DETAILS =
  "people/ REQUEST FETCH PEOPLE DETAILS";
export const FETCH_PEOPLE_DETAILS_SUCCESS =
  "people/ FETCH PEOPLE DETAILS SUCCESS";
export const FETCH_PEOPLE_DETAILS_FAIL = "people/ FETCH PEOPLE DETAILS FAIL";

export const REQUEST_FETCH_PEOPLE_CREDITS =
  "people/ REQUEST FETCH PEOPLE CREDITS";
export const FETCH_PEOPLE_CREDITS_SUCCESS =
  "people/ FETCH PEOPLE CREDITS SUCCESS";
export const FETCH_PEOPLE_CREDITS_FAIL = "people/ FETCH PEOPLE CREDITS FAIL";
export const CLEAR_PEOPLE_CREDITS = "people/ CLEAR PEOPLE CREDITS";
